name         'camptocamp-postfix'
version      '0.2.0'
source       'https://github.com/camptocamp/puppet-postfix'
author       'Camptocamp'
license      'Apache 2.0'
summary      'Camptocamp Postfix Module'
description  'Postfix Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-postfix'
